spring:
  datasource:
    url: jdbc:mysql://172.17.0.11:3306/official_vehicle?useUnicode=true&characterEncoding=utf-8
    username: root
    password: laintime@7
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
  ## Freemarker 配置
  ## 文件配置路径
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
server:
  port: 8080
weixin:
  mp:
    token:
    AppID: wxe8bf23ae502e5b85
    AppSecret: fafa91c6a0420ea32b91c6431b7fc51b
gizwits:
  gizwitsAppId: b435696d0d584861bef43772242e6494
  gizwitsAppSecret: 8d3756a589054fae8590140798409977
  gizwitsProductKey: 5ed794bcf1d54595931500426b55d347
  gizwitsProductSecret: 1e86afbaf1024fbb97903abd0d32c032